bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVAPPEARCHARACTER001.MSB txt\ja\MSB\EVAPPEARCHARACTER001.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVAPPEARCHARACTER002.MSB txt\ja\MSB\EVAPPEARCHARACTER002.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVAPPEARCHARACTER003.MSB txt\ja\MSB\EVAPPEARCHARACTER003.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVAPPEARCHARACTER004.MSB txt\ja\MSB\EVAPPEARCHARACTER004.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVAPPEARCHARACTER005.MSB txt\ja\MSB\EVAPPEARCHARACTER005.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVAPPEARCHARACTER006.MSB txt\ja\MSB\EVAPPEARCHARACTER006.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVAPPEARCHARACTER007.MSB txt\ja\MSB\EVAPPEARCHARACTER007.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVAPPEARCHARACTER008.MSB txt\ja\MSB\EVAPPEARCHARACTER008.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVAPPEARCHARACTER009.MSB txt\ja\MSB\EVAPPEARCHARACTER009.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVAPPEARCHARACTER010.MSB txt\ja\MSB\EVAPPEARCHARACTER010.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVAPPEARCHARACTER103.MSB txt\ja\MSB\EVAPPEARCHARACTER103.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVCLEARFREEQUEST00090.MSB txt\ja\MSB\EVCLEARFREEQUEST00090.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVNOTRETURN.MSB txt\ja\MSB\EVNOTRETURN.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVOPENSONGINFO002_1.MSB txt\ja\MSB\EVOPENSONGINFO002_1.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVOPENSONGINFO002_2.MSB txt\ja\MSB\EVOPENSONGINFO002_2.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVOPENSONGINFO002_3.MSB txt\ja\MSB\EVOPENSONGINFO002_3.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVOPENSONGINFO002_4.MSB txt\ja\MSB\EVOPENSONGINFO002_4.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVOPENSONGINFO002_5.MSB txt\ja\MSB\EVOPENSONGINFO002_5.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVOPENSONGINFO002_6.MSB txt\ja\MSB\EVOPENSONGINFO002_6.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVOPENSONGINFO002_7.MSB txt\ja\MSB\EVOPENSONGINFO002_7.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVOPENSONGINFO002_8.MSB txt\ja\MSB\EVOPENSONGINFO002_8.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVOPENSONGINFO003_1.MSB txt\ja\MSB\EVOPENSONGINFO003_1.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVOPENSONGINFO007_1.MSB txt\ja\MSB\EVOPENSONGINFO007_1.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVRETURNAZEL.MSB txt\ja\MSB\EVRETURNAZEL.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVRETURNCHARACTER002.MSB txt\ja\MSB\EVRETURNCHARACTER002.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVRETURNCHARACTER004.MSB txt\ja\MSB\EVRETURNCHARACTER004.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVRETURNCHARACTER005.MSB txt\ja\MSB\EVRETURNCHARACTER005.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVRETURNCHARACTER006.MSB txt\ja\MSB\EVRETURNCHARACTER006.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVRETURNCHARACTER007.MSB txt\ja\MSB\EVRETURNCHARACTER007.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVRETURNCHARACTER008.MSB txt\ja\MSB\EVRETURNCHARACTER008.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSAVESEQUENCE201.MSB txt\ja\MSB\EVSAVESEQUENCE201.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSAVESEQUENCE235.MSB txt\ja\MSB\EVSAVESEQUENCE235.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSAVESEQUENCE251.MSB txt\ja\MSB\EVSAVESEQUENCE251.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSAVESEQUENCEEND.MSB txt\ja\MSB\EVSAVESEQUENCEEND.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSECESSIONCHARACTER.MSB txt\ja\MSB\EVSECESSIONCHARACTER.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETMODEPOSSESSION0201.MSB txt\ja\MSB\EVSETMODEPOSSESSION0201.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETMODEPOSSESSION0202.MSB txt\ja\MSB\EVSETMODEPOSSESSION0202.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETMODEPOSSESSION0203.MSB txt\ja\MSB\EVSETMODEPOSSESSION0203.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETMODEPOSSESSION0204.MSB txt\ja\MSB\EVSETMODEPOSSESSION0204.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0110.MSB txt\ja\MSB\EVSETNEWPERSONALITY0110.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0111.MSB txt\ja\MSB\EVSETNEWPERSONALITY0111.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0120.MSB txt\ja\MSB\EVSETNEWPERSONALITY0120.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0130.MSB txt\ja\MSB\EVSETNEWPERSONALITY0130.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0131.MSB txt\ja\MSB\EVSETNEWPERSONALITY0131.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0220.MSB txt\ja\MSB\EVSETNEWPERSONALITY0220.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0221.MSB txt\ja\MSB\EVSETNEWPERSONALITY0221.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0230.MSB txt\ja\MSB\EVSETNEWPERSONALITY0230.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0231.MSB txt\ja\MSB\EVSETNEWPERSONALITY0231.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0300.MSB txt\ja\MSB\EVSETNEWPERSONALITY0300.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0320.MSB txt\ja\MSB\EVSETNEWPERSONALITY0320.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0330.MSB txt\ja\MSB\EVSETNEWPERSONALITY0330.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0331.MSB txt\ja\MSB\EVSETNEWPERSONALITY0331.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0420.MSB txt\ja\MSB\EVSETNEWPERSONALITY0420.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0430.MSB txt\ja\MSB\EVSETNEWPERSONALITY0430.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0431.MSB txt\ja\MSB\EVSETNEWPERSONALITY0431.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0520.MSB txt\ja\MSB\EVSETNEWPERSONALITY0520.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0530.MSB txt\ja\MSB\EVSETNEWPERSONALITY0530.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0531.MSB txt\ja\MSB\EVSETNEWPERSONALITY0531.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0600.MSB txt\ja\MSB\EVSETNEWPERSONALITY0600.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0601.MSB txt\ja\MSB\EVSETNEWPERSONALITY0601.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0620.MSB txt\ja\MSB\EVSETNEWPERSONALITY0620.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0630.MSB txt\ja\MSB\EVSETNEWPERSONALITY0630.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0631.MSB txt\ja\MSB\EVSETNEWPERSONALITY0631.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0710.MSB txt\ja\MSB\EVSETNEWPERSONALITY0710.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0720.MSB txt\ja\MSB\EVSETNEWPERSONALITY0720.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0730.MSB txt\ja\MSB\EVSETNEWPERSONALITY0730.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0820.MSB txt\ja\MSB\EVSETNEWPERSONALITY0820.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0830.MSB txt\ja\MSB\EVSETNEWPERSONALITY0830.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0831.MSB txt\ja\MSB\EVSETNEWPERSONALITY0831.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0920.MSB txt\ja\MSB\EVSETNEWPERSONALITY0920.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0930.MSB txt\ja\MSB\EVSETNEWPERSONALITY0930.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSETNEWPERSONALITY0931.MSB txt\ja\MSB\EVSETNEWPERSONALITY0931.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSTAMPATELIER.MSB txt\ja\MSB\EVSTAMPATELIER.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSTAMPBAKERY.MSB txt\ja\MSB\EVSTAMPBAKERY.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSTAMPCARDFIRST.MSB txt\ja\MSB\EVSTAMPCARDFIRST.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVSTAMPITEMSHOP.MSB txt\ja\MSB\EVSTAMPITEMSHOP.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN01.MSB txt\ja\MSB\EVTOWNOPEN01.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN02.MSB txt\ja\MSB\EVTOWNOPEN02.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN03.MSB txt\ja\MSB\EVTOWNOPEN03.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN04.MSB txt\ja\MSB\EVTOWNOPEN04.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN05.MSB txt\ja\MSB\EVTOWNOPEN05.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN07.MSB txt\ja\MSB\EVTOWNOPEN07.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN08.MSB txt\ja\MSB\EVTOWNOPEN08.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN09.MSB txt\ja\MSB\EVTOWNOPEN09.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN10.MSB txt\ja\MSB\EVTOWNOPEN10.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN11.MSB txt\ja\MSB\EVTOWNOPEN11.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN12.MSB txt\ja\MSB\EVTOWNOPEN12.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTOWNOPEN13.MSB txt\ja\MSB\EVTOWNOPEN13.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET01.MSB txt\ja\MSB\EVTROPHYGET01.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET02.MSB txt\ja\MSB\EVTROPHYGET02.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET03.MSB txt\ja\MSB\EVTROPHYGET03.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET04.MSB txt\ja\MSB\EVTROPHYGET04.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET05.MSB txt\ja\MSB\EVTROPHYGET05.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET06.MSB txt\ja\MSB\EVTROPHYGET06.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET07.MSB txt\ja\MSB\EVTROPHYGET07.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET08.MSB txt\ja\MSB\EVTROPHYGET08.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET09.MSB txt\ja\MSB\EVTROPHYGET09.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET10.MSB txt\ja\MSB\EVTROPHYGET10.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET11.MSB txt\ja\MSB\EVTROPHYGET11.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET15.MSB txt\ja\MSB\EVTROPHYGET15.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET16.MSB txt\ja\MSB\EVTROPHYGET16.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET17.MSB txt\ja\MSB\EVTROPHYGET17.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET18.MSB txt\ja\MSB\EVTROPHYGET18.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET19.MSB txt\ja\MSB\EVTROPHYGET19.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET20.MSB txt\ja\MSB\EVTROPHYGET20.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET21.MSB txt\ja\MSB\EVTROPHYGET21.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET22.MSB txt\ja\MSB\EVTROPHYGET22.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET23.MSB txt\ja\MSB\EVTROPHYGET23.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET24.MSB txt\ja\MSB\EVTROPHYGET24.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET25.MSB txt\ja\MSB\EVTROPHYGET25.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET26.MSB txt\ja\MSB\EVTROPHYGET26.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET27.MSB txt\ja\MSB\EVTROPHYGET27.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET28.MSB txt\ja\MSB\EVTROPHYGET28.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET29.MSB txt\ja\MSB\EVTROPHYGET29.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVTROPHYGET30.MSB txt\ja\MSB\EVTROPHYGET30.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\EVWAKEUP.MSB txt\ja\MSB\EVWAKEUP.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00402.MSB txt\ja\MSB\NT00402.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00403.MSB txt\ja\MSB\NT00403.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00404.MSB txt\ja\MSB\NT00404.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00405.MSB txt\ja\MSB\NT00405.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00406.MSB txt\ja\MSB\NT00406.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00407.MSB txt\ja\MSB\NT00407.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00408.MSB txt\ja\MSB\NT00408.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00409.MSB txt\ja\MSB\NT00409.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00501.MSB txt\ja\MSB\NT00501.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00502.MSB txt\ja\MSB\NT00502.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00503.MSB txt\ja\MSB\NT00503.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00504.MSB txt\ja\MSB\NT00504.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00505.MSB txt\ja\MSB\NT00505.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00506.MSB txt\ja\MSB\NT00506.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00507.MSB txt\ja\MSB\NT00507.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00508.MSB txt\ja\MSB\NT00508.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00509.MSB txt\ja\MSB\NT00509.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00510.MSB txt\ja\MSB\NT00510.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00511.MSB txt\ja\MSB\NT00511.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00512.MSB txt\ja\MSB\NT00512.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00513.MSB txt\ja\MSB\NT00513.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00514.MSB txt\ja\MSB\NT00514.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00515.MSB txt\ja\MSB\NT00515.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00516.MSB txt\ja\MSB\NT00516.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00517.MSB txt\ja\MSB\NT00517.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00518.MSB txt\ja\MSB\NT00518.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00519.MSB txt\ja\MSB\NT00519.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00520.MSB txt\ja\MSB\NT00520.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00521.MSB txt\ja\MSB\NT00521.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00522.MSB txt\ja\MSB\NT00522.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00523.MSB txt\ja\MSB\NT00523.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00524.MSB txt\ja\MSB\NT00524.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00525.MSB txt\ja\MSB\NT00525.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00526.MSB txt\ja\MSB\NT00526.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT00528.MSB txt\ja\MSB\NT00528.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT01001.MSB txt\ja\MSB\NT01001.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT02003.MSB txt\ja\MSB\NT02003.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT03002.MSB txt\ja\MSB\NT03002.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT03004.MSB txt\ja\MSB\NT03004.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT04003.MSB txt\ja\MSB\NT04003.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT05004.MSB txt\ja\MSB\NT05004.txt
bin\Sb\Sb\bin\Debug\sb.exe -msb2txt isofiles\DATA_extract\NT05005.MSB txt\ja\MSB\NT05005.txt
REM -----------------------------------------------------------------------------------------
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_ADVERTISE.MTP txt\ja\MTP\MTPA_ADVERTISE.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV10100.MTP   txt\ja\MTP\MTPA_EV10100.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV10200.MTP   txt\ja\MTP\MTPA_EV10200.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV10300.MTP   txt\ja\MTP\MTPA_EV10300.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV10400.MTP   txt\ja\MTP\MTPA_EV10400.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV10500.MTP   txt\ja\MTP\MTPA_EV10500.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV10600.MTP   txt\ja\MTP\MTPA_EV10600.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV10700.MTP   txt\ja\MTP\MTPA_EV10700.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV10800.MTP   txt\ja\MTP\MTPA_EV10800.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV10900.MTP   txt\ja\MTP\MTPA_EV10900.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV20100.MTP   txt\ja\MTP\MTPA_EV20100.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV20200.MTP   txt\ja\MTP\MTPA_EV20200.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV20300.MTP   txt\ja\MTP\MTPA_EV20300.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV20400.MTP   txt\ja\MTP\MTPA_EV20400.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV20500.MTP   txt\ja\MTP\MTPA_EV20500.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV20600.MTP   txt\ja\MTP\MTPA_EV20600.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV20700.MTP   txt\ja\MTP\MTPA_EV20700.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV20800.MTP   txt\ja\MTP\MTPA_EV20800.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV20900.MTP   txt\ja\MTP\MTPA_EV20900.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV30200.MTP   txt\ja\MTP\MTPA_EV30200.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV30300.MTP   txt\ja\MTP\MTPA_EV30300.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV30400.MTP   txt\ja\MTP\MTPA_EV30400.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV30500.MTP   txt\ja\MTP\MTPA_EV30500.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV30600.MTP   txt\ja\MTP\MTPA_EV30600.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV30700.MTP   txt\ja\MTP\MTPA_EV30700.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV30800.MTP   txt\ja\MTP\MTPA_EV30800.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV39100.MTP   txt\ja\MTP\MTPA_EV39100.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV39200.MTP   txt\ja\MTP\MTPA_EV39200.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV39300.MTP   txt\ja\MTP\MTPA_EV39300.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV39400.MTP   txt\ja\MTP\MTPA_EV39400.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV39500.MTP   txt\ja\MTP\MTPA_EV39500.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV40100.MTP   txt\ja\MTP\MTPA_EV40100.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV40200.MTP   txt\ja\MTP\MTPA_EV40200.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV40300.MTP   txt\ja\MTP\MTPA_EV40300.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV50100.MTP   txt\ja\MTP\MTPA_EV50100.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV50200.MTP   txt\ja\MTP\MTPA_EV50200.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV50300.MTP   txt\ja\MTP\MTPA_EV50300.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV50400.MTP   txt\ja\MTP\MTPA_EV50400.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV50500.MTP   txt\ja\MTP\MTPA_EV50500.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV50600.MTP   txt\ja\MTP\MTPA_EV50600.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV50700.MTP   txt\ja\MTP\MTPA_EV50700.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV50800.MTP   txt\ja\MTP\MTPA_EV50800.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV50900.MTP   txt\ja\MTP\MTPA_EV50900.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV52100.MTP   txt\ja\MTP\MTPA_EV52100.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV52200.MTP   txt\ja\MTP\MTPA_EV52200.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV52300.MTP   txt\ja\MTP\MTPA_EV52300.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV52400.MTP   txt\ja\MTP\MTPA_EV52400.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV52500.MTP   txt\ja\MTP\MTPA_EV52500.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV52600.MTP   txt\ja\MTP\MTPA_EV52600.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV52700.MTP   txt\ja\MTP\MTPA_EV52700.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV52800.MTP   txt\ja\MTP\MTPA_EV52800.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV60000.MTP   txt\ja\MTP\MTPA_EV60000.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV60100.MTP   txt\ja\MTP\MTPA_EV60100.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV60200.MTP   txt\ja\MTP\MTPA_EV60200.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV60300.MTP   txt\ja\MTP\MTPA_EV60300.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV60400.MTP   txt\ja\MTP\MTPA_EV60400.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV60500.MTP   txt\ja\MTP\MTPA_EV60500.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV60600.MTP   txt\ja\MTP\MTPA_EV60600.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV60700.MTP   txt\ja\MTP\MTPA_EV60700.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV60800.MTP   txt\ja\MTP\MTPA_EV60800.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV60900.MTP   txt\ja\MTP\MTPA_EV60900.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_EV62000.MTP   txt\ja\MTP\MTPA_EV62000.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_GAME.MTP      txt\ja\MTP\MTPA_GAME.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_SLG.MTP       txt\ja\MTP\MTPA_SLG.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_SYS.MTP       txt\ja\MTP\MTPA_SYS.txt
bin\Sb\Sb\bin\Debug\sb.exe -mtp2txt isofiles\DATA_extract\MTPA_TOWN.MTP      txt\ja\MTP\MTPA_TOWN.txt