mkdir isofiles\DATA_new
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVAPPEARCHARACTER001.MSB	txt\en\MSB\EVAPPEARCHARACTER001.txt	isofiles\DATA_new\EVAPPEARCHARACTER001.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVAPPEARCHARACTER002.MSB	txt\en\MSB\EVAPPEARCHARACTER002.txt	isofiles\DATA_new\EVAPPEARCHARACTER002.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVAPPEARCHARACTER003.MSB	txt\en\MSB\EVAPPEARCHARACTER003.txt	isofiles\DATA_new\EVAPPEARCHARACTER003.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVAPPEARCHARACTER004.MSB	txt\en\MSB\EVAPPEARCHARACTER004.txt	isofiles\DATA_new\EVAPPEARCHARACTER004.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVAPPEARCHARACTER005.MSB	txt\en\MSB\EVAPPEARCHARACTER005.txt	isofiles\DATA_new\EVAPPEARCHARACTER005.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVAPPEARCHARACTER006.MSB	txt\en\MSB\EVAPPEARCHARACTER006.txt	isofiles\DATA_new\EVAPPEARCHARACTER006.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVAPPEARCHARACTER007.MSB	txt\en\MSB\EVAPPEARCHARACTER007.txt	isofiles\DATA_new\EVAPPEARCHARACTER007.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVAPPEARCHARACTER008.MSB	txt\en\MSB\EVAPPEARCHARACTER008.txt	isofiles\DATA_new\EVAPPEARCHARACTER008.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVAPPEARCHARACTER009.MSB	txt\en\MSB\EVAPPEARCHARACTER009.txt	isofiles\DATA_new\EVAPPEARCHARACTER009.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVAPPEARCHARACTER010.MSB	txt\en\MSB\EVAPPEARCHARACTER010.txt	isofiles\DATA_new\EVAPPEARCHARACTER010.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVAPPEARCHARACTER103.MSB	txt\en\MSB\EVAPPEARCHARACTER103.txt	isofiles\DATA_new\EVAPPEARCHARACTER103.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVCLEARFREEQUEST00090.MSB	txt\en\MSB\EVCLEARFREEQUEST00090.txt	isofiles\DATA_new\EVCLEARFREEQUEST00090.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVNOTRETURN.MSB	txt\en\MSB\EVNOTRETURN.txt	isofiles\DATA_new\EVNOTRETURN.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVOPENSONGINFO002_1.MSB	txt\en\MSB\EVOPENSONGINFO002_1.txt	isofiles\DATA_new\EVOPENSONGINFO002_1.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVOPENSONGINFO002_2.MSB	txt\en\MSB\EVOPENSONGINFO002_2.txt	isofiles\DATA_new\EVOPENSONGINFO002_2.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVOPENSONGINFO002_3.MSB	txt\en\MSB\EVOPENSONGINFO002_3.txt	isofiles\DATA_new\EVOPENSONGINFO002_3.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVOPENSONGINFO002_4.MSB	txt\en\MSB\EVOPENSONGINFO002_4.txt	isofiles\DATA_new\EVOPENSONGINFO002_4.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVOPENSONGINFO002_5.MSB	txt\en\MSB\EVOPENSONGINFO002_5.txt	isofiles\DATA_new\EVOPENSONGINFO002_5.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVOPENSONGINFO002_6.MSB	txt\en\MSB\EVOPENSONGINFO002_6.txt	isofiles\DATA_new\EVOPENSONGINFO002_6.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVOPENSONGINFO002_7.MSB	txt\en\MSB\EVOPENSONGINFO002_7.txt	isofiles\DATA_new\EVOPENSONGINFO002_7.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVOPENSONGINFO002_8.MSB	txt\en\MSB\EVOPENSONGINFO002_8.txt	isofiles\DATA_new\EVOPENSONGINFO002_8.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVOPENSONGINFO003_1.MSB	txt\en\MSB\EVOPENSONGINFO003_1.txt	isofiles\DATA_new\EVOPENSONGINFO003_1.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVOPENSONGINFO007_1.MSB	txt\en\MSB\EVOPENSONGINFO007_1.txt	isofiles\DATA_new\EVOPENSONGINFO007_1.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVRETURNAZEL.MSB	txt\en\MSB\EVRETURNAZEL.txt	isofiles\DATA_new\EVRETURNAZEL.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVRETURNCHARACTER002.MSB	txt\en\MSB\EVRETURNCHARACTER002.txt	isofiles\DATA_new\EVRETURNCHARACTER002.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVRETURNCHARACTER004.MSB	txt\en\MSB\EVRETURNCHARACTER004.txt	isofiles\DATA_new\EVRETURNCHARACTER004.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVRETURNCHARACTER005.MSB	txt\en\MSB\EVRETURNCHARACTER005.txt	isofiles\DATA_new\EVRETURNCHARACTER005.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVRETURNCHARACTER006.MSB	txt\en\MSB\EVRETURNCHARACTER006.txt	isofiles\DATA_new\EVRETURNCHARACTER006.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVRETURNCHARACTER007.MSB	txt\en\MSB\EVRETURNCHARACTER007.txt	isofiles\DATA_new\EVRETURNCHARACTER007.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVRETURNCHARACTER008.MSB	txt\en\MSB\EVRETURNCHARACTER008.txt	isofiles\DATA_new\EVRETURNCHARACTER008.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSAVESEQUENCE201.MSB	txt\en\MSB\EVSAVESEQUENCE201.txt	isofiles\DATA_new\EVSAVESEQUENCE201.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSAVESEQUENCE235.MSB	txt\en\MSB\EVSAVESEQUENCE235.txt	isofiles\DATA_new\EVSAVESEQUENCE235.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSAVESEQUENCE251.MSB	txt\en\MSB\EVSAVESEQUENCE251.txt	isofiles\DATA_new\EVSAVESEQUENCE251.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSAVESEQUENCEEND.MSB	txt\en\MSB\EVSAVESEQUENCEEND.txt	isofiles\DATA_new\EVSAVESEQUENCEEND.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSECESSIONCHARACTER.MSB	txt\en\MSB\EVSECESSIONCHARACTER.txt	isofiles\DATA_new\EVSECESSIONCHARACTER.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETMODEPOSSESSION0201.MSB	txt\en\MSB\EVSETMODEPOSSESSION0201.txt	isofiles\DATA_new\EVSETMODEPOSSESSION0201.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETMODEPOSSESSION0202.MSB	txt\en\MSB\EVSETMODEPOSSESSION0202.txt	isofiles\DATA_new\EVSETMODEPOSSESSION0202.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETMODEPOSSESSION0203.MSB	txt\en\MSB\EVSETMODEPOSSESSION0203.txt	isofiles\DATA_new\EVSETMODEPOSSESSION0203.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETMODEPOSSESSION0204.MSB	txt\en\MSB\EVSETMODEPOSSESSION0204.txt	isofiles\DATA_new\EVSETMODEPOSSESSION0204.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0110.MSB	txt\en\MSB\EVSETNEWPERSONALITY0110.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0110.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0111.MSB	txt\en\MSB\EVSETNEWPERSONALITY0111.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0111.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0120.MSB	txt\en\MSB\EVSETNEWPERSONALITY0120.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0120.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0130.MSB	txt\en\MSB\EVSETNEWPERSONALITY0130.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0130.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0131.MSB	txt\en\MSB\EVSETNEWPERSONALITY0131.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0131.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0220.MSB	txt\en\MSB\EVSETNEWPERSONALITY0220.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0220.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0221.MSB	txt\en\MSB\EVSETNEWPERSONALITY0221.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0221.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0230.MSB	txt\en\MSB\EVSETNEWPERSONALITY0230.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0230.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0231.MSB	txt\en\MSB\EVSETNEWPERSONALITY0231.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0231.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0300.MSB	txt\en\MSB\EVSETNEWPERSONALITY0300.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0300.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0320.MSB	txt\en\MSB\EVSETNEWPERSONALITY0320.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0320.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0330.MSB	txt\en\MSB\EVSETNEWPERSONALITY0330.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0330.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0331.MSB	txt\en\MSB\EVSETNEWPERSONALITY0331.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0331.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0420.MSB	txt\en\MSB\EVSETNEWPERSONALITY0420.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0420.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0430.MSB	txt\en\MSB\EVSETNEWPERSONALITY0430.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0430.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0431.MSB	txt\en\MSB\EVSETNEWPERSONALITY0431.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0431.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0520.MSB	txt\en\MSB\EVSETNEWPERSONALITY0520.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0520.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0530.MSB	txt\en\MSB\EVSETNEWPERSONALITY0530.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0530.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0531.MSB	txt\en\MSB\EVSETNEWPERSONALITY0531.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0531.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0600.MSB	txt\en\MSB\EVSETNEWPERSONALITY0600.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0600.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0601.MSB	txt\en\MSB\EVSETNEWPERSONALITY0601.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0601.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0620.MSB	txt\en\MSB\EVSETNEWPERSONALITY0620.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0620.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0630.MSB	txt\en\MSB\EVSETNEWPERSONALITY0630.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0630.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0631.MSB	txt\en\MSB\EVSETNEWPERSONALITY0631.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0631.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0710.MSB	txt\en\MSB\EVSETNEWPERSONALITY0710.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0710.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0720.MSB	txt\en\MSB\EVSETNEWPERSONALITY0720.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0720.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0730.MSB	txt\en\MSB\EVSETNEWPERSONALITY0730.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0730.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0820.MSB	txt\en\MSB\EVSETNEWPERSONALITY0820.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0820.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0830.MSB	txt\en\MSB\EVSETNEWPERSONALITY0830.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0830.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0831.MSB	txt\en\MSB\EVSETNEWPERSONALITY0831.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0831.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0920.MSB	txt\en\MSB\EVSETNEWPERSONALITY0920.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0920.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0930.MSB	txt\en\MSB\EVSETNEWPERSONALITY0930.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0930.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSETNEWPERSONALITY0931.MSB	txt\en\MSB\EVSETNEWPERSONALITY0931.txt	isofiles\DATA_new\EVSETNEWPERSONALITY0931.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSTAMPATELIER.MSB	txt\en\MSB\EVSTAMPATELIER.txt	isofiles\DATA_new\EVSTAMPATELIER.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSTAMPBAKERY.MSB	txt\en\MSB\EVSTAMPBAKERY.txt	isofiles\DATA_new\EVSTAMPBAKERY.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSTAMPCARDFIRST.MSB	txt\en\MSB\EVSTAMPCARDFIRST.txt	isofiles\DATA_new\EVSTAMPCARDFIRST.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVSTAMPITEMSHOP.MSB	txt\en\MSB\EVSTAMPITEMSHOP.txt	isofiles\DATA_new\EVSTAMPITEMSHOP.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN01.MSB	txt\en\MSB\EVTOWNOPEN01.txt	isofiles\DATA_new\EVTOWNOPEN01.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN02.MSB	txt\en\MSB\EVTOWNOPEN02.txt	isofiles\DATA_new\EVTOWNOPEN02.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN03.MSB	txt\en\MSB\EVTOWNOPEN03.txt	isofiles\DATA_new\EVTOWNOPEN03.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN04.MSB	txt\en\MSB\EVTOWNOPEN04.txt	isofiles\DATA_new\EVTOWNOPEN04.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN05.MSB	txt\en\MSB\EVTOWNOPEN05.txt	isofiles\DATA_new\EVTOWNOPEN05.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN07.MSB	txt\en\MSB\EVTOWNOPEN07.txt	isofiles\DATA_new\EVTOWNOPEN07.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN08.MSB	txt\en\MSB\EVTOWNOPEN08.txt	isofiles\DATA_new\EVTOWNOPEN08.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN09.MSB	txt\en\MSB\EVTOWNOPEN09.txt	isofiles\DATA_new\EVTOWNOPEN09.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN10.MSB	txt\en\MSB\EVTOWNOPEN10.txt	isofiles\DATA_new\EVTOWNOPEN10.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN11.MSB	txt\en\MSB\EVTOWNOPEN11.txt	isofiles\DATA_new\EVTOWNOPEN11.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN12.MSB	txt\en\MSB\EVTOWNOPEN12.txt	isofiles\DATA_new\EVTOWNOPEN12.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTOWNOPEN13.MSB	txt\en\MSB\EVTOWNOPEN13.txt	isofiles\DATA_new\EVTOWNOPEN13.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET01.MSB	txt\en\MSB\EVTROPHYGET01.txt	isofiles\DATA_new\EVTROPHYGET01.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET02.MSB	txt\en\MSB\EVTROPHYGET02.txt	isofiles\DATA_new\EVTROPHYGET02.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET03.MSB	txt\en\MSB\EVTROPHYGET03.txt	isofiles\DATA_new\EVTROPHYGET03.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET04.MSB	txt\en\MSB\EVTROPHYGET04.txt	isofiles\DATA_new\EVTROPHYGET04.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET05.MSB	txt\en\MSB\EVTROPHYGET05.txt	isofiles\DATA_new\EVTROPHYGET05.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET06.MSB	txt\en\MSB\EVTROPHYGET06.txt	isofiles\DATA_new\EVTROPHYGET06.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET07.MSB	txt\en\MSB\EVTROPHYGET07.txt	isofiles\DATA_new\EVTROPHYGET07.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET08.MSB	txt\en\MSB\EVTROPHYGET08.txt	isofiles\DATA_new\EVTROPHYGET08.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET09.MSB	txt\en\MSB\EVTROPHYGET09.txt	isofiles\DATA_new\EVTROPHYGET09.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET10.MSB	txt\en\MSB\EVTROPHYGET10.txt	isofiles\DATA_new\EVTROPHYGET10.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET11.MSB	txt\en\MSB\EVTROPHYGET11.txt	isofiles\DATA_new\EVTROPHYGET11.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET15.MSB	txt\en\MSB\EVTROPHYGET15.txt	isofiles\DATA_new\EVTROPHYGET15.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET16.MSB	txt\en\MSB\EVTROPHYGET16.txt	isofiles\DATA_new\EVTROPHYGET16.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET17.MSB	txt\en\MSB\EVTROPHYGET17.txt	isofiles\DATA_new\EVTROPHYGET17.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET18.MSB	txt\en\MSB\EVTROPHYGET18.txt	isofiles\DATA_new\EVTROPHYGET18.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET19.MSB	txt\en\MSB\EVTROPHYGET19.txt	isofiles\DATA_new\EVTROPHYGET19.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET20.MSB	txt\en\MSB\EVTROPHYGET20.txt	isofiles\DATA_new\EVTROPHYGET20.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET21.MSB	txt\en\MSB\EVTROPHYGET21.txt	isofiles\DATA_new\EVTROPHYGET21.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET22.MSB	txt\en\MSB\EVTROPHYGET22.txt	isofiles\DATA_new\EVTROPHYGET22.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET23.MSB	txt\en\MSB\EVTROPHYGET23.txt	isofiles\DATA_new\EVTROPHYGET23.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET24.MSB	txt\en\MSB\EVTROPHYGET24.txt	isofiles\DATA_new\EVTROPHYGET24.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET25.MSB	txt\en\MSB\EVTROPHYGET25.txt	isofiles\DATA_new\EVTROPHYGET25.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET26.MSB	txt\en\MSB\EVTROPHYGET26.txt	isofiles\DATA_new\EVTROPHYGET26.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET27.MSB	txt\en\MSB\EVTROPHYGET27.txt	isofiles\DATA_new\EVTROPHYGET27.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET28.MSB	txt\en\MSB\EVTROPHYGET28.txt	isofiles\DATA_new\EVTROPHYGET28.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET29.MSB	txt\en\MSB\EVTROPHYGET29.txt	isofiles\DATA_new\EVTROPHYGET29.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVTROPHYGET30.MSB	txt\en\MSB\EVTROPHYGET30.txt	isofiles\DATA_new\EVTROPHYGET30.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\EVWAKEUP.MSB	txt\en\MSB\EVWAKEUP.txt	isofiles\DATA_new\EVWAKEUP.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00402.MSB	txt\en\MSB\NT00402.txt	isofiles\DATA_new\NT00402.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00403.MSB	txt\en\MSB\NT00403.txt	isofiles\DATA_new\NT00403.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00404.MSB	txt\en\MSB\NT00404.txt	isofiles\DATA_new\NT00404.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00405.MSB	txt\en\MSB\NT00405.txt	isofiles\DATA_new\NT00405.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00406.MSB	txt\en\MSB\NT00406.txt	isofiles\DATA_new\NT00406.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00407.MSB	txt\en\MSB\NT00407.txt	isofiles\DATA_new\NT00407.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00408.MSB	txt\en\MSB\NT00408.txt	isofiles\DATA_new\NT00408.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00409.MSB	txt\en\MSB\NT00409.txt	isofiles\DATA_new\NT00409.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00501.MSB	txt\en\MSB\NT00501.txt	isofiles\DATA_new\NT00501.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00502.MSB	txt\en\MSB\NT00502.txt	isofiles\DATA_new\NT00502.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00503.MSB	txt\en\MSB\NT00503.txt	isofiles\DATA_new\NT00503.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00504.MSB	txt\en\MSB\NT00504.txt	isofiles\DATA_new\NT00504.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00505.MSB	txt\en\MSB\NT00505.txt	isofiles\DATA_new\NT00505.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00506.MSB	txt\en\MSB\NT00506.txt	isofiles\DATA_new\NT00506.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00507.MSB	txt\en\MSB\NT00507.txt	isofiles\DATA_new\NT00507.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00508.MSB	txt\en\MSB\NT00508.txt	isofiles\DATA_new\NT00508.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00509.MSB	txt\en\MSB\NT00509.txt	isofiles\DATA_new\NT00509.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00510.MSB	txt\en\MSB\NT00510.txt	isofiles\DATA_new\NT00510.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00511.MSB	txt\en\MSB\NT00511.txt	isofiles\DATA_new\NT00511.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00512.MSB	txt\en\MSB\NT00512.txt	isofiles\DATA_new\NT00512.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00513.MSB	txt\en\MSB\NT00513.txt	isofiles\DATA_new\NT00513.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00514.MSB	txt\en\MSB\NT00514.txt	isofiles\DATA_new\NT00514.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00515.MSB	txt\en\MSB\NT00515.txt	isofiles\DATA_new\NT00515.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00516.MSB	txt\en\MSB\NT00516.txt	isofiles\DATA_new\NT00516.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00517.MSB	txt\en\MSB\NT00517.txt	isofiles\DATA_new\NT00517.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00518.MSB	txt\en\MSB\NT00518.txt	isofiles\DATA_new\NT00518.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00519.MSB	txt\en\MSB\NT00519.txt	isofiles\DATA_new\NT00519.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00520.MSB	txt\en\MSB\NT00520.txt	isofiles\DATA_new\NT00520.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00521.MSB	txt\en\MSB\NT00521.txt	isofiles\DATA_new\NT00521.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00522.MSB	txt\en\MSB\NT00522.txt	isofiles\DATA_new\NT00522.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00523.MSB	txt\en\MSB\NT00523.txt	isofiles\DATA_new\NT00523.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00524.MSB	txt\en\MSB\NT00524.txt	isofiles\DATA_new\NT00524.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00525.MSB	txt\en\MSB\NT00525.txt	isofiles\DATA_new\NT00525.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00526.MSB	txt\en\MSB\NT00526.txt	isofiles\DATA_new\NT00526.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT00528.MSB	txt\en\MSB\NT00528.txt	isofiles\DATA_new\NT00528.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT01001.MSB	txt\en\MSB\NT01001.txt	isofiles\DATA_new\NT01001.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT02003.MSB	txt\en\MSB\NT02003.txt	isofiles\DATA_new\NT02003.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT03002.MSB	txt\en\MSB\NT03002.txt	isofiles\DATA_new\NT03002.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT03004.MSB	txt\en\MSB\NT03004.txt	isofiles\DATA_new\NT03004.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT04003.MSB	txt\en\MSB\NT04003.txt	isofiles\DATA_new\NT04003.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT05004.MSB	txt\en\MSB\NT05004.txt	isofiles\DATA_new\NT05004.MSB
bin\Sb\Sb\bin\Debug\sb.exe	-txt2msb	isofiles\DATA_extract\NT05005.MSB	txt\en\MSB\NT05005.txt	isofiles\DATA_new\NT05005.MSB
REM -----------------------------------------------------------------------------------------
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_ADVERTISE.MTP	txt\en\MTP\MTPA_ADVERTISE.txt	isofiles\DATA_new\MTPA_ADVERTISE.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV10100.MTP	txt\en\MTP\MTPA_EV10100.txt	isofiles\DATA_new\MTPA_EV10100.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV10200.MTP	txt\en\MTP\MTPA_EV10200.txt	isofiles\DATA_new\MTPA_EV10200.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV10300.MTP	txt\en\MTP\MTPA_EV10300.txt	isofiles\DATA_new\MTPA_EV10300.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV10400.MTP	txt\en\MTP\MTPA_EV10400.txt	isofiles\DATA_new\MTPA_EV10400.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV10500.MTP	txt\en\MTP\MTPA_EV10500.txt	isofiles\DATA_new\MTPA_EV10500.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV10600.MTP	txt\en\MTP\MTPA_EV10600.txt	isofiles\DATA_new\MTPA_EV10600.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV10700.MTP	txt\en\MTP\MTPA_EV10700.txt	isofiles\DATA_new\MTPA_EV10700.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV10800.MTP	txt\en\MTP\MTPA_EV10800.txt	isofiles\DATA_new\MTPA_EV10800.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV10900.MTP	txt\en\MTP\MTPA_EV10900.txt	isofiles\DATA_new\MTPA_EV10900.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV20100.MTP	txt\en\MTP\MTPA_EV20100.txt	isofiles\DATA_new\MTPA_EV20100.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV20200.MTP	txt\en\MTP\MTPA_EV20200.txt	isofiles\DATA_new\MTPA_EV20200.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV20300.MTP	txt\en\MTP\MTPA_EV20300.txt	isofiles\DATA_new\MTPA_EV20300.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV20400.MTP	txt\en\MTP\MTPA_EV20400.txt	isofiles\DATA_new\MTPA_EV20400.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV20500.MTP	txt\en\MTP\MTPA_EV20500.txt	isofiles\DATA_new\MTPA_EV20500.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV20600.MTP	txt\en\MTP\MTPA_EV20600.txt	isofiles\DATA_new\MTPA_EV20600.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV20700.MTP	txt\en\MTP\MTPA_EV20700.txt	isofiles\DATA_new\MTPA_EV20700.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV20800.MTP	txt\en\MTP\MTPA_EV20800.txt	isofiles\DATA_new\MTPA_EV20800.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV20900.MTP	txt\en\MTP\MTPA_EV20900.txt	isofiles\DATA_new\MTPA_EV20900.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV30200.MTP	txt\en\MTP\MTPA_EV30200.txt	isofiles\DATA_new\MTPA_EV30200.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV30300.MTP	txt\en\MTP\MTPA_EV30300.txt	isofiles\DATA_new\MTPA_EV30300.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV30400.MTP	txt\en\MTP\MTPA_EV30400.txt	isofiles\DATA_new\MTPA_EV30400.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV30500.MTP	txt\en\MTP\MTPA_EV30500.txt	isofiles\DATA_new\MTPA_EV30500.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV30600.MTP	txt\en\MTP\MTPA_EV30600.txt	isofiles\DATA_new\MTPA_EV30600.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV30700.MTP	txt\en\MTP\MTPA_EV30700.txt	isofiles\DATA_new\MTPA_EV30700.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV30800.MTP	txt\en\MTP\MTPA_EV30800.txt	isofiles\DATA_new\MTPA_EV30800.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV39100.MTP	txt\en\MTP\MTPA_EV39100.txt	isofiles\DATA_new\MTPA_EV39100.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV39200.MTP	txt\en\MTP\MTPA_EV39200.txt	isofiles\DATA_new\MTPA_EV39200.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV39300.MTP	txt\en\MTP\MTPA_EV39300.txt	isofiles\DATA_new\MTPA_EV39300.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV39400.MTP	txt\en\MTP\MTPA_EV39400.txt	isofiles\DATA_new\MTPA_EV39400.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV39500.MTP	txt\en\MTP\MTPA_EV39500.txt	isofiles\DATA_new\MTPA_EV39500.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV40100.MTP	txt\en\MTP\MTPA_EV40100.txt	isofiles\DATA_new\MTPA_EV40100.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV40200.MTP	txt\en\MTP\MTPA_EV40200.txt	isofiles\DATA_new\MTPA_EV40200.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV40300.MTP	txt\en\MTP\MTPA_EV40300.txt	isofiles\DATA_new\MTPA_EV40300.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV50100.MTP	txt\en\MTP\MTPA_EV50100.txt	isofiles\DATA_new\MTPA_EV50100.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV50200.MTP	txt\en\MTP\MTPA_EV50200.txt	isofiles\DATA_new\MTPA_EV50200.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV50300.MTP	txt\en\MTP\MTPA_EV50300.txt	isofiles\DATA_new\MTPA_EV50300.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV50400.MTP	txt\en\MTP\MTPA_EV50400.txt	isofiles\DATA_new\MTPA_EV50400.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV50500.MTP	txt\en\MTP\MTPA_EV50500.txt	isofiles\DATA_new\MTPA_EV50500.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV50600.MTP	txt\en\MTP\MTPA_EV50600.txt	isofiles\DATA_new\MTPA_EV50600.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV50700.MTP	txt\en\MTP\MTPA_EV50700.txt	isofiles\DATA_new\MTPA_EV50700.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV50800.MTP	txt\en\MTP\MTPA_EV50800.txt	isofiles\DATA_new\MTPA_EV50800.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV50900.MTP	txt\en\MTP\MTPA_EV50900.txt	isofiles\DATA_new\MTPA_EV50900.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV52100.MTP	txt\en\MTP\MTPA_EV52100.txt	isofiles\DATA_new\MTPA_EV52100.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV52200.MTP	txt\en\MTP\MTPA_EV52200.txt	isofiles\DATA_new\MTPA_EV52200.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV52300.MTP	txt\en\MTP\MTPA_EV52300.txt	isofiles\DATA_new\MTPA_EV52300.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV52400.MTP	txt\en\MTP\MTPA_EV52400.txt	isofiles\DATA_new\MTPA_EV52400.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV52500.MTP	txt\en\MTP\MTPA_EV52500.txt	isofiles\DATA_new\MTPA_EV52500.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV52600.MTP	txt\en\MTP\MTPA_EV52600.txt	isofiles\DATA_new\MTPA_EV52600.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV52700.MTP	txt\en\MTP\MTPA_EV52700.txt	isofiles\DATA_new\MTPA_EV52700.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV52800.MTP	txt\en\MTP\MTPA_EV52800.txt	isofiles\DATA_new\MTPA_EV52800.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV60000.MTP	txt\en\MTP\MTPA_EV60000.txt	isofiles\DATA_new\MTPA_EV60000.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV60100.MTP	txt\en\MTP\MTPA_EV60100.txt	isofiles\DATA_new\MTPA_EV60100.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV60200.MTP	txt\en\MTP\MTPA_EV60200.txt	isofiles\DATA_new\MTPA_EV60200.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV60300.MTP	txt\en\MTP\MTPA_EV60300.txt	isofiles\DATA_new\MTPA_EV60300.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV60400.MTP	txt\en\MTP\MTPA_EV60400.txt	isofiles\DATA_new\MTPA_EV60400.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV60500.MTP	txt\en\MTP\MTPA_EV60500.txt	isofiles\DATA_new\MTPA_EV60500.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV60600.MTP	txt\en\MTP\MTPA_EV60600.txt	isofiles\DATA_new\MTPA_EV60600.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV60700.MTP	txt\en\MTP\MTPA_EV60700.txt	isofiles\DATA_new\MTPA_EV60700.MTP
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV60800.MTP  txt\en\MTP\MTPA_EV60800.txt isofiles\DATA_new\MTPA_EV60800.MTP  
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV60900.MTP  txt\en\MTP\MTPA_EV60900.txt isofiles\DATA_new\MTPA_EV60900.MTP  
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_EV62000.MTP  txt\en\MTP\MTPA_EV62000.txt isofiles\DATA_new\MTPA_EV62000.MTP  
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_GAME.MTP     txt\en\MTP\MTPA_GAME.txt    isofiles\DATA_new\MTPA_GAME.MTP     
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_SLG.MTP      txt\en\MTP\MTPA_SLG.txt     isofiles\DATA_new\MTPA_SLG.MTP      
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_SYS.MTP      txt\en\MTP\MTPA_SYS.txt     isofiles\DATA_new\MTPA_SYS.MTP      
bin\Sb\Sb\bin\Debug\sb.exe	-txt2mtp	isofiles\DATA_extract\MTPA_TOWN.MTP     txt\en\MTP\MTPA_TOWN.txt    isofiles\DATA_new\MTPA_TOWN.MTP     